/** Константы для авторизации */
export const AUTH_FETCHING = 'AUTH_FETCHING';
export const AUTH_REQUEST_SENDD = 'AUTH_REQUEST_SENDD';
export const AUTH_REQUEST_SUCCESSED = 'AUTH_REQUEST_SUCCESSED';
export const START_REQUEST_SUCCESSED = 'START_REQUEST_SUCCESSED';

/** Константы для категории*/
export const CATALOG_FETCHING = 'CATALOG_FETCHING';
export const CATALOG_REQUEST_SENDD = 'CATALOG_REQUEST_SENDD';
export const CATALOG_REQUEST_SUCCESSED = 'CATALOG_REQUEST_SUCCESSED';
export const CATALOG_POST = 'CATALOG_POST';
export const CATALOG_UPDATE = 'CATALOG_UPDATE';

/** Константы для параметров*/
export const PROPERTY_POST = 'PROPERTY_POST';

/** Константы для опций*/
export const OPTION_POST = 'OPTION_POST';

/** Константы для инцидентов */
export const INCIDENT_FETCHING = 'INCIDENT_FETCHING';
export const INCIDENT_REQUEST_SENDD = 'INCIDENT_REQUEST_SENDD';
export const INCIDENT_REQUEST_SUCCESSED = 'INCIDENT_REQUEST_SUCCESSED';
export const INCIDENT_CREATE = 'INCIDENT_CREATE';
export const INCIDENT_CHOOSE = 'INCIDENT_CHOOSE';
export const MY_INCIDENT_REQUEST_SUCCESSED = 'MY_INCIDENT_REQUEST_SUCCESSED';
export const INCIDENT_HISTORY_REQUEST_SUCCESSED =
  'INCIDENT_HISTORY_REQUEST_SUCCESSED';

/** Константы для отделов */
export const DEPARTMENT_FETCHING = 'DEPARTMENT_FETCHING';
export const DEPARTMENT_REQUEST_SENDD = 'DEPARTMENT_REQUEST_SENDD';
export const DEPARTMENT_REQUEST_SUCCESSED = 'DEPARTMENT_REQUEST_SUCCESSED';

/** Запрос REST API */
export const QUERY_API = 'QUERY_API';

/** Константы для статус */
export const STATUS_REQUEST_SUCCESSED = 'STATUS_REQUEST_SUCCESSED';
export const STATUS_UPDATE = 'STATUS_UPDATE';

/**Должности */
export const POSITIONS_REQUEST_SUCCESSED = 'POSITIONS_REQUEST_SUCCESSED';
export const POSITIONS_UPDATE = 'POSITIONS_UPDATE';

/**Пользователи */
export const USERS_REQUEST_SUCCESSED = 'USERS_REQUEST_SUCCESSED';
export const USERS_UPDATE = 'USERS_UPDATE';
export const USERS_CURRENT_REQUEST_SUCCESSED =
  'USERS_CURRENT_REQUEST_SUCCESSED';
export const USERS_CURRENT_UPDATE = 'USERS_CURRENT_UPDATE';

/**ERROR_CLOSE */
export const ERROR_CLOSE = 'ERROR_CLOSE';

/**Пользователи */
export const ACCESS_REQUEST_SUCCESSED = 'ACCESS_REQUEST_SUCCESSED';
export const ACCESS_UPDATE = 'ACCESS_UPDATE';

/**Пользователи */
export const FILE_FETCHING = 'FILE_FETCHING';
export const FILE_REQUEST_SENDD = 'FILE_REQUEST_SENDD';
export const FILE_REQUEST_SUCCESSED = 'FILE_REQUEST_SUCCESSED';

//** Progress Bar */

export const PROGRESS_START = 'PROGRESS_START';
export const PROGRESS_STEP = 'PROGRESS_STEP';
export const PROGRESS_FINISH = 'PROGRESS_FINISH';
