/** Константы для авторизации */
export const AUTH_FETCHING = 'AUTH_FETCHING';
export const AUTH_REQUEST_SENDD = 'AUTH_REQUEST_SENDD';
export const AUTH_REQUEST_SUCCESSED = 'AUTH_REQUEST_SUCCESSED';

/** Константы для категории*/
export const CATALOG_FETCHING = 'CATALOG_FETCHING';
export const CATALOG_REQUEST_SENDD = 'CATALOG_REQUEST_SENDD';
export const CATALOG_REQUEST_SUCCESSED = 'CATALOG_REQUEST_SUCCESSED';
export const CATALOG_POST = 'CATALOG_POST';
export const CATALOG_UPDATE = 'CATALOG_UPDATE';

/** Константы для параметров*/
export const PROPERTY_POST = 'PROPERTY_POST';

/** Константы для опций*/
export const OPTION_POST = 'OPTION_POST';

/** Константы для инцидентов */
export const INCIDENT_FETCHING = 'INCIDENT_FETCHING';
export const INCIDENT_REQUEST_SENDD = 'INCIDENT_REQUEST_SENDD';
export const INCIDENT_REQUEST_SUCCESSED = 'INCIDENT_REQUEST_SUCCESSED';
export const INCIDENT_CREATE = 'INCIDENT_CREATE';
export const INCIDENT_CHOOSE = 'INCIDENT_CHOOSE';
export const MY_INCIDENT_REQUEST_SUCCESSED = 'MY_INCIDENT_REQUEST_SUCCESSED';
export const INCIDENT_HISTORY_REQUEST_SUCCESSED =
  'INCIDENT_HISTORY_REQUEST_SUCCESSED';

/** Константы для отделов */
export const DEPARTMENT_FETCHING = 'DEPARTMENT_FETCHING';
export const DEPARTMENT_REQUEST_SENDD = 'DEPARTMENT_REQUEST_SENDD';
export const DEPARTMENT_REQUEST_SUCCESSED = 'DEPARTMENT_REQUEST_SUCCESSED';

/** Запрос REST API */
export const QUERY_API = 'QUERY_API';

/** Константы для статус */
export const STATUS_REQUEST_SUCCESSED = 'STATUS_REQUEST_SUCCESSED';
export const STATUS_UPDATE = 'STATUS_UPDATE';
