/** Константы для авторизации */
export const AUTH_FETCHING = 'AUTH_FETCHING';
export const AUTH_REQUEST_SENDD = 'AUTH_REQUEST_SENDD';
export const AUTH_REQUEST_SUCCESSED = 'AUTH_REQUEST_SUCCESSED';

/** Константы для категории*/
export const CATEGOTY_FETCHING = 'CATEGOTY_FETCHING';
export const CATEGOTY_REQUEST_SENDD = 'CATEGOTY_REQUEST_SENDD';
export const CATEGOTY_REQUEST_SUCCESSED = 'CATEGOTY_REQUEST_SUCCESSED';
